services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/app/logs
    environment:
      - TZ=Europe/Moscow
    restart: unless-stopped
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge